name: manual release
on: [workflow_dispatch]

env:
  PACKAGE_NAME: pymer4
  DEPLOY_PY_VER: 3.8  # only this job deploys docs, anaconda.org, pypi
  DEPLOY_OS: ubuntu-latest
  CONDA_BLD_PATH: /tmp/ci_conda_bld

defaults:
  run:
    # login shell to source the conda hook in .bash_profile
    shell:
      bash -l {0}

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        py_ver: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-11]  # Intel macs

    outputs:
      # tarballs are py3X job-specific
      conda-tarball: ${{ steps.conda-bld.outputs.conda-tarball }}

    steps:

      # ------------------------------------------------------------
      # 0. Print some basic github action info
      - name: diagnostic info
        run: |
          echo "OS: ${{ matrix.os }}" 
          echo "Python: ${{ matrix.py_ver }}" 
          echo "Conda build path: $CONDA_BLD_PATH"
          echo "Deploy OS: $DEPLOY_OS"
          echo "Deploy Python: $DEPLOY_PY_VER"
          echo "GA event name: ${{ github.event_name }}"
          echo "GA ref: ${{ github.ref }}"

      # ------------------------------------------------------------
      # 1. Grab git repo, setup miniconda environment and packages required to build
      - uses: actions/checkout@v2
      - name: Setup Miniconda + Checkout code
        run: |
          echo "GIT_ABBREV_COMMIT=_g${GITHUB_SHA:0:8}" >> $GITHUB_ENV

          if [[ ${{ runner.os }} == Linux ]]; then \
            miniconda_url='https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh'; \
          fi
          if [[ ${{ runner.os }} == macOS ]]; then \
            miniconda_url='https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh'; \
          fi

          wget $miniconda_url -O $HOME/miniconda.sh
          bash ~/miniconda.sh -b -p $HOME/miniconda
          hash -r
          $HOME/miniconda/bin/conda shell.bash hook >> ~/.bash_profile  
          source ~/.bash_profile
          
          hash -r
          conda config --set always_yes yes --set changeps1 no
          conda config --set bld_path $CONDA_BLD_PATH
          conda install -n base -q conda-build conda-verify anaconda-client
          echo "# ------------------------------------------------------------"
          conda info -a

      # ------------------------------------------------------------
      # 2. Build the conda package and tarballs for each OS
      # env defined here are just for convenience when writing bash commands
      - name: Build package
        id: conda-bld
        env:
          OS: ${{ runner.os }}   
          PY_VER: ${{ matrix.py_ver }}
        run: |
          conda build --python=$PY_VER -c defaults -c conda-forge conda
          tarball=$(conda build --python=$PY_VER conda --output | tail -1)
          if [[ $OS == "Linux" ]]; then \
              conda convert -p win-64 -o $CONDA_BLD_PATH $tarball; \
          fi
          echo "conda build tarball" $tarball
          echo "::set-output name=conda-tarball::$tarball"

      # ------------------------------------------------------------
      # 3. Create new conda env and install package locally
      # Test installation worked
      # Get black and pytest from pip because black version on conda lags behind
      - name: Create and test fresh installation 
        env:
          PY_VER: ${{ matrix.py_ver }}
        run: |
          conda create -n env_$PY_VER python=$PY_VER $PACKAGE_NAME 'blas=*=mkl' -c $CONDA_BLD_PATH -c defaults -c conda-forge
          conda activate env_$PY_VER
          pip install black pytest-cov
          conda list
          lscpu
          python -c 'import numpy; numpy.show_config()'
          python -c "from pymer4.test_install import test_install; test_install()"

      # 6. Build package for PyPi (only for 3.8 linux which handles deployment)
      - name: Build for Pypi
        if: ${{ matrix.py_ver == env.DEPLOY_PY_VER && matrix.os == env.DEPLOY_OS }}
        run: |
          conda activate env_$PY_VER
          pip install build
          python -m build --sdist --wheel --outdir dist/
      
      # 7. Deploy package to Pypi (only need to do this once on linux)
      - name: PyPi deploy
        if: ${{ matrix.py_ver == env.DEPLOY_PY_VER && matrix.os == env.DEPLOY_OS }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      # 8a. Deploy package to main conda channel (only for 3.8 which handles deployment) but each OS uploads their own and linux uploads for linux and windows
      - name: Conda main deploy 
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          echo 'Conda release on main channel'
          anaconda -t "$ANACONDA_TOKEN" upload $CONDA_BLD_PATH/**/${PACKAGE_NAME}*.tar.bz2 -l "main"
